/* FightEndo – offline cache. Only caches the app's own files; never sends data.
 * SPDX-License-Identifier: GPL-3.0-or-later */
// BEGIN:files – generated by `npm run sync`, do not edit by hand
const CACHE = 'fightendo-d904494553';
const FILES = [
  './',
  './index.html',
  './privacy.html',
  './impressum.html',
  './css/app.css',
  './js/core.js',
  './js/pdf.js',
  './js/native.js',
  './js/signature.js',
  './js/app.js',
  './icons/icon.svg',
  './icons/icon-192.webp',
  './icons/icon-512.webp',
  './manifest.webmanifest',
  './i18n/de.js',
  './i18n/en.js',
  './jurisdictions/de/index.js'
];
// END:files

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(FILES)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  e.waitUntil(caches.keys()
    .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
    .then(() => self.clients.claim()));
});

self.addEventListener('fetch', (e) => {
  if (e.request.method !== 'GET' || new URL(e.request.url).origin !== location.origin) return;
  // Network first so updates arrive; the cache keeps the app usable offline.
  e.respondWith(fetch(e.request).then((res) => {
    const copy = res.clone();
    caches.open(CACHE).then((c) => c.put(e.request, copy));
    return res;
  }).catch(() => caches.match(e.request)));
});
